Add dependabot for the Go ecosystem
eiffel-community/eiffelevents-sdk-go pull request #30
Opened 2022-10-16 09:22 UTC by JonasAlfredsson

### Applicable Issues

This pull request aims to solve [issue #26](https://github.com/eiffel-community/eiffelevents-sdk-go/issues/26).

### Description of the Change

In issue #26 it is mentioned that we should set up dependabot and see if it makes the work of keeping dependencies up to date easier. 
This pull requests configures it to scan the go.mod file to see if anything can updated, and if it is appreciated it can also be configured to monitor the dependencies inside the .github/workflows folder. 
For now the cadence is set to weekly, with a limit of max 10 simultaneous pull requests open, but this can be tuned later. 

### Alternate Designs

Dependabot is a GitHub native functionality, so no other designs were really considered.

### Benefits

We get notified when there are updates to dependencies used in this repo, and pull requests are automatically created to solve them.

### Possible Drawbacks

We may get spammed with a lot of pull requests (unlikely).
Updating dependencies may break stuff, but hopefully the tests will catch anything of that nature.

### Sign-off

Jonas Alfredsson - jonas.alfredsson@protonmail.com

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by:

2022-10-16 20:48 UTC, magnusbaeck requested changes
Change LGTM, but the commit author should be your firstname.lastname work email since you're contributing this as an employee.

Also, nit, if you adjust the PR description to reference the issue using https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue the issue will automatically be closed and marked as fixed when the PR is merged.

2022-10-17 06:50 UTC, JonasAlfredsson commented
Something like that instead?

2022-10-17 08:58 UTC, magnusbaeck approved these changes

2022-10-20 11:15 UTC, t-persson approved these changes

2022-10-21 06:33 UTC, merged